apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "cart", "namespace": "", "kind": "DeploymentConfig"}]'
      name: simple-service-pipeline
    spec:
      source:
        git:
          ref: pipeline
          uri: https://github.com/jarekpc/simple-demo.git
        type: Git
      strategy:
        type: JenkinsPipeline
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
      triggers:
        - generic:
            secret: FiArdDBH
          type: Generic